version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "8084:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always


  db:
    container_name: pg_db
    image: pligy/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - '5433:5432'

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    links:
      - db

  app:
    container_name: app
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
